### ISSUE TITLE
Experimental `documentMiddleware` option that this relies on has been removed from nextjs

### ISSUE THREAD

**Issue by benvium** [labd/nextjs-basic-auth-middleware#11]
.. as of April 2020.

:-(

See here:
https://github.com/vercel/next.js/pull/12218

Shame as this library looked useful. Presumably there's no easy way around this.

**Comment by rubenpoppe** [comment]
Have you tried without the experimental option? I'm running this config and still get the login alert.
```
module.exports = {
    poweredByHeader: false,
};
```

**Comment by kkomelin** [comment]
Can also confirm that the http basic auth is working without the experimental configuration option.

**Comment by blurrah** [comment]
I have updated the documentation to remove the experimental flag.

**Comment by kkomelin** [comment]
Thanks @blurrah !
