### ISSUE TITLE
TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by lionelyoung** [labd/nextjs-basic-auth-middleware#2]
I created a _document.js to make a Custom Document, per https://nextjs.org/docs/advanced-features/custom-document

I'm getting the error `TypeError: Cannot read property 'url' of undefined`

Here's my pages/_document.js:
```js
import Document, { Html, Head, Main, NextScript } from 'next/document'
import basicAuthMiddleware from 'nextjs-basic-auth-middleware'



class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx)
    await basicAuthMiddleware(ctx["req"], ctx["res"], {})
    return { ...initialProps }
  }

  render() {
    return (
      <Html>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument


```

**Comment by rumtraubenuss** [comment]
Make sure to run the middleware only on the serverside.
```
const initialProps = await Document.getInitialProps(ctx)
if(process.browser) {
  return { ...initialProps };
}
await basicAuthMiddleware(ctx["req"], ctx["res"], {});
return { ...initialProps };
```

**Comment by webdeb** [comment]
same issue with `next@10.0.2`

**Comment by kkomelin** [comment]
same with next@10.0.8

**Comment by blurrah** [comment]
Hi, I've just published `v0.2.1` that should fix this issue. This was originally created for projects that had pages that always defined a `getInitialProps` method which is why it never popped up for me.

Let me know if you run into any other issues.

**Comment by kkomelin** [comment]
Thanks for your effort @blurrah! Will test the solution in my spare time and let you know if there are any issues.

**Comment by kkomelin** [comment]
Tried with Document-level middleware and it didn't work for some reason. No error messages.

**Comment by pazams** [comment]
> Tried with Document-level middleware and it didn't work for some reason. No error messages.

I had the same issue when rendering the top level index page. Adding this to `pages/index.js` solved it
```js
export async function getServerSideProps(context) {
  return {
    props: {}, 
  }
}
```

See also https://stackoverflow.com/a/65791568

**Comment by kkomelin** [comment]
Thanks @pazams
