### ISSUE TITLE
Authorize to user who doesn't input username or password!

### ISSUE THREAD

**Issue by cr1315** [labd/nextjs-basic-auth-middleware#4]
This code would cause `input.username = "" && input.password === password` or `input.username = username && input.password === ""` authorized.  
Apparently, it **SHOULD NOT**!

```javascript
valid =
compare(
  user.name,
  requiredCredentials.find(item => item.name === user.name)?.name ?? ''
) && valid
valid =
compare(
  user.pass,
  requiredCredentials.find(item => item.password === user.pass)?.password ??
    ''
) && valid
```

**Comment by thiagops** [comment]
I can reproduce. This has stopped us using this library in production, unfortunately.

- Do not enter neither a username nor a password;
- You are granted access;
- Expected behaviour: access should have been denied.

**Comment by leobaldoneto** [comment]
Is that resolved?

**Comment by cr1315** [comment]
> Is that resolved?

It seems not, well if you don't mind, you can use [this](https://www.npmjs.com/package/@ray4105/nextjs-basic-auth-middleware) for a hurry.

**Comment by blurrah** [comment]
Oh man that's a really big error on my part, sorry! Have made a PR with a fix and will merge and release it.
