### ISSUE TITLE
Cannot read property 'realm' of undefined

### ISSUE THREAD

**Issue by jimfilippou** [labd/nextjs-basic-auth-middleware#7]
![image](https://user-images.githubusercontent.com/6877046/97602287-cc58bb00-1a13-11eb-97b0-1f9c602ecc9f.png)

**Comment by HaNdTriX** [comment]
The experimental option that made this module possible was removed:

> This option was experimental and doesn't cover the hybrid nature of Next.js of today (both static and dynamic pages). It also doesn't cover the cases we wanted to cover with the option. The option also does not work in all targets and is an avenue for slowing down the application.

https://github.com/vercel/next.js/pull/12218

So your own option is to downgrade Next.js for the time being.

**Comment by jimfilippou** [comment]
Thanks @HaNdTriX 

For future viewers of this thread, I am mentioning ways to work around this below 👇 

### Option 1
As @HaNdTriX said, you can downgrade next version and use this API at the version which is supported. The downside of this way is that you cannot update next.js to any future updates, so I do recommend option 2 below.

### Option 2
You can skip this library and use basic auth on an express server on top of your next application. You can do it this way 
```javascript
const next = require('next');
const express = require('express');
const auth = require('basic-auth');

const dev = process.env.NODE_ENV === 'development'
const app = next({ dev })
const handle = app.getRequestHandler()

app.prepare()
  .then(() => {
    const server = express()

    server.use(function (req, res, next) {
      const credentials = auth(req)
      if (!credentials || credentials.name !== 'admin' || credentials.pass !== '123456') {
        res.status(401)
        res.header('WWW-Authenticate', 'Basic realm="example"')
        res.send('Access denied')
      } else {
        next()
      }
    });

    server.get('*', (req, res) => {
      return handle(req, res)
    })

    const port = 3000;
    server.listen(port, (err) => {
      if (err) {
        throw err
      }
      console.log(`Ready on http://localhost:${port}`)
    })
  })
  .catch((ex) => {
    console.error(ex.stack)
    process.exit(1)
  })
```
